# Generated by Django 3.1.7 on 2021-04-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('panel', '0001_initial'), ('panel', '0002_auto_20210413_2231'), ('panel', '0003_auto_20210413_2235'), ('panel', '0004_auto_20210413_2237')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('code', models.UUIDField(auto_created=True, primary_key=True, serialize=False, verbose_name='Ticket code')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('passes', models.IntegerField(default=0, verbose_name='Passes')),
                ('category', models.CharField(default='defcat', max_length=200, verbose_name='Category')),
                ('comments', models.CharField(max_length=2000, null=True, verbose_name='Comments')),
                ('cost', models.CharField(max_length=20, null=True, verbose_name='Cost')),
            ],
        ),
    ]
