# Generated by Django 3.1.7 on 2021-04-15 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('code', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Ticket code')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('passes', models.IntegerField(default=0, verbose_name='Passes')),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
                ('order', models.IntegerField(default=None, null=True, verbose_name='Order')),
                ('cost', models.CharField(max_length=20, null=True, verbose_name='Cost')),
                ('comments', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
        ),
    ]
